### ISSUE TITLE
BetterEnd Weapon heads don't have valid recipes

### ISSUE THREAD

**Issue by AngelTechnic** [KodoDenka/knavesneeds#14]
Thallasium, Terminite, and Aeternium weapons cannot be crafted in survival because their corresponding tool heads cannot be forged in an anvil (and have no other recipes).

**Comment by KodoDenka** [comment]
Just an update to let you know I am indeed working on it. I reached out to the creator of BetterEnd/Nether who also makes the library I use for those recipes.

It seems to be an issue on their end, but I'll try to have this fixed as soon as possible.

**Comment by KodoDenka** [comment]
Fixed with 1.1.5.1
