### ISSUE TITLE
incompatible with bclib

### ISSUE THREAD

**Issue by gitguette** [KodoDenka/knavesneeds#16]
crash report: [crash-2023-07-23-client.txt](https://github.com/KodoDenka/knavesneeds/files/12142590/crash-2023-07-23_23.38.40-client.txt)

**Comment by gitguette** [comment]
update: found the incompatible mod: bclib(used for better nether and end mods)

**Comment by Sunconure11** [comment]
Encountering the same error too.

@KodoDenka

**Comment by Sunconure11** [comment]
https://pastebin.com/8we66qSu

**Comment by KodoDenka** [comment]
Fixed with 1.1.5.1

**Comment by Sunconure11** [comment]
My version of the error is on 1.19.2. Will there be a build to fix it there or no?

**Comment by gitguette** [comment]
> My version of the error is on 1.19.2. Will there be a build to fix it there or no?

yep!

**Comment by Sunconure11** [comment]
I already saw it got a fix.
