### ISSUE TITLE
Mod compat with Levelz

### ISSUE THREAD

**Issue by SamuelUlep** [KodoDenka/knavesneeds#17]
I have the mod Simply swords and Levelz installed but not mythic metal or gobber, despite levelz seems to be incompatible with simply swords, will this be fixable with Knaves' needs or do I need to contact the creator of Levelz?
![image](https://github.com/KodoDenka/knavesneeds/assets/129558275/1540b3f8-a5fc-4fef-9165-db11ea500cfc)

**Comment by gitguette** [comment]
what is incompatible? you can add custom level requirements if that's the issue.

**Comment by DanDragonWolf** [comment]
Simply Swords is advertised to work with LevelZ

**Comment by DanDragonWolf** [comment]
And even though the items don't exist without Mythic Metals or Gobber installed, Simply Swords still adds them to the LevelZ weapon list

**Comment by SamuelUlep** [comment]
Sorry I phrased it wrong, does Knaves needs fixes the appearance of gobber/mythic metals weapon versions of weapons even when those mods are not installed?

**Comment by KodoDenka** [comment]
Knaves Needs doesn't change any Simply Sword content.
