### ISSUE TITLE
Some weapon models are rendered wrongly in third person

### ISSUE THREAD

**Issue by NeuTraLZero** [KodoDenka/knavesneeds#27]
Blue Skies halberds are rendered very small
![image](https://github.com/KodoDenka/knavesneeds/assets/43245485/4de2a92d-b7b3-4e2b-bb72-80b0d6386fe3)
![image](https://github.com/KodoDenka/knavesneeds/assets/43245485/a09a5f0a-3249-41f3-b2c0-f73ed805bb33)

**Comment by NeuTraLZero** [comment]
Every greataxes are also held slightly off (This is with every greataxes, not just from Blue Skies)
![image](https://github.com/KodoDenka/knavesneeds/assets/43245485/5f6b29cd-e975-4acd-b7fb-1609439755e8)

This is what it should look like
![image](https://github.com/KodoDenka/knavesneeds/assets/43245485/631d53c1-d0b4-4066-85ed-fd1bc487621f)

**Comment by KodoDenka** [comment]
Which version of Minecraft is this happening on?

**Comment by KodoDenka** [comment]
Ah, found the issue. Fixed in 1.20.1+
