### ISSUE TITLE
Missing recipes for Draco Arcanus Katana and Scythe

### ISSUE THREAD

**Issue by NeuTraLZero** [KodoDenka/knavesneeds#28]
![image](https://github.com/KodoDenka/knavesneeds/assets/43245485/25d074e9-3041-4676-84de-6c2b93253787)
![image](https://github.com/KodoDenka/knavesneeds/assets/43245485/56eabe9c-8fd4-4a8c-9a11-b19d1d345989)

**Comment by KodoDenka** [comment]
Fixed in version 2.0.1+
