### ISSUE TITLE
Not recognizing forbidden and arcanus 

### ISSUE THREAD

**Issue by yahi-ko** [KodoDenka/knavesneeds#3]
Not recognizing forbidden and arcanus leading to crash even though i have it installed

Unsupported installed optional dependencies:
	Mod ID: 'forbidden_arcanus', Requested by: 'knavesneeds', Expected range: '[2.1.0,)', Actual version: '1.19.2-2.1.0'

**Comment by BouncyWouncyWoo** [comment]
Experiencing this as well, happens with both 2.1.0 and 2.1.1 of FA.

**Comment by KodoDenka** [comment]
Yep, this is my bad. Forbidden Arcanus wants the MC version and mod version in it's identifier. I'll have this soon ASAP. (10-12 hours.)

**Comment by KodoDenka** [comment]
Fixed as of version 1.0.3
