### ISSUE TITLE
Can't craft or locate recipes for new items

### ISSUE THREAD

**Issue by BouncyWouncyWoo** [KodoDenka/knavesneeds#4]
Really happy to see this updated for 1.9.2. Ran into the below issues while testing the new items out.

- I can't seem to make any of new additions and trying to find their recipes with Roughly Enough Items' recipe browser brings up nothing.
- None of them have item names, they're all listed as item.blue_skies.horizonite.spear, item.blue_skies.horizonite.katana etc.

Happy to provide additional testing if it helps.

**Comment by KodoDenka** [comment]
This is completely my fault, I did major refactoring of the project late at night and apparently forgot to finish it. I know what this issue is now,  I'll have this fixed within 10-12 hours. (I'd do it sooner but I'm at work.) I sincerely apologize for my mistake.

**Comment by KodoDenka** [comment]
This is completely my fault, I did major refactoring of the project late at night and apparently forgot to finish it. I know what this issue is now,  I'll have this fixed within 10-12 hours. (I'd do it sooner but I'm at work.) I sincerely apologize for my mistake.

**Comment by KodoDenka** [comment]
This is completely my fault, I did major refactoring of the project late at night and apparently forgot to finish it. I know what this issue is now,  I'll have this fixed within 10-12 hours. (I'd do it sooner but I'm at work.) I sincerely apologize for my mistake.

**Comment by BouncyWouncyWoo** [comment]
No worries, mistakes happen mate. Take your time and thanks for your hard work .

**Comment by KodoDenka** [comment]
Fixed as of version 1.0.3
