### ISSUE TITLE
In 1.18.2, the game won't launch without its "optional" dependencies

### ISSUE THREAD

**Issue by LordDarthDan** [KodoDenka/knavesneeds#5]
Exatly that: when I tried to launch it with just Better Combat and Simply swords, it demanded Forbidden and Arcanus, then Undergarden...

I understand that version is Beta but I don't think it's a huge fix.

**Comment by KodoDenka** [comment]
I shouldn't have been a big fix, but I made a lot of mistakes while creating the mod. Which led me to create a slightly less broken version for 1.19.2. I'm patching that version up currently, and once that is in a better state I'll be porting it forward and backwards.

TL:DR - 1.18 is currently beyond broken, a new version will be coming at some point. :tm:

**Comment by LordDarthDan** [comment]
I see. Am making a pack rn... Guess I'll have to keep an eye out and perhaps add it in one of the future updates.

**Comment by KodoDenka** [comment]
Knaves' Needs' most recent version has been backported to 1.18.2. If any other problems happen just let me know.
