### ISSUE TITLE
Pendorite Weapons Do Less Damage Than Netherite

### ISSUE THREAD

**Issue by RiftSpatial** [KodoDenka/knavesneeds#6]
Pendorite weapons seem to do less damage than netherite. While a netherite sword (8 damage) plus a pendorite ingot gives you a pendorite sword that does 9 damage, I'll just use the longsword as an example, a netherite longsword (8 damage) plus a pendorite ingot gives you a pendorite longsword that does 5 damage! Most of the pendorite weapons do 5 damage when most of the netherite weapons do 8.

**Comment by KodoDenka** [comment]
I did a bunch of the weapon damage calculations wrong, going back through patching holes. This will be fixed next update as well.
