### ISSUE TITLE
Draco Arcanus Weapon of the Forbidden Arcanus mod are not craftable

### ISSUE THREAD

**Issue by TimelessKeeper** [KodoDenka/knavesneeds#8]
The Draco Arcanus Weapon of the Forbidden Arcanus mod are not craftable.

- The recipe don't appear in JEI when looking for the recipe

**Comment by KodoDenka** [comment]
Forbidden Arcanus has been on of the harder mods for me to support... they keep renaming things internally, breaking my mod. I'll get this fixed next update, thanks for the report.
