### ISSUE TITLE
[1.19.2] Game crashes on load if better combat isn't installed.

### ISSUE THREAD

**Issue by Darkmega18** [KodoDenka/knavesneeds#9]
Issue to go with my comment on curseforge of: _I thought you said better combat was "highly recommended", not "needed unless you want to crash". :V_

Just sent the whole latest log. it crashes fairly early on, before the game can really come up. but I can't tell if it's yours or simply swords itself cause yours needs simply swords to work in the first place. but I'd expect it was yours cause of the other person having a possibly similar issue.

[latest.log](https://github.com/KodoDenka/knavesneeds/files/11050086/latest.log)

**Comment by KodoDenka** [comment]
Fixed.
